In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [78]:
common_args = {
    "sep": ";",
    "encoding": "latin-1",
    "engine": "python",
    "on_bad_lines": "skip",
    "quoting": 3  
}

books = pd.read_csv("books_data/books.csv", **common_args)
users = pd.read_csv("books_data/users.csv", **common_args)
ratings = pd.read_csv("books_data/ratings.csv", **common_args)

In [79]:
books.head(2)

,"""ISBN""","""Book-Title""","""Book-Author""","""Year-Of-Publication""","""Publisher""","""Image-URL-S""","""Image-URL-M""","""Image-URL-L"""
0,"""0195153448""","""Classical Mythology""","""Mark P. O. Morford""","""2002""","""Oxford University Press""","""http://images.amazon.com/images/P/0195153448....","""http://images.amazon.com/images/P/0195153448....","""http://images.amazon.com/images/P/0195153448...."
1,"""0002005018""","""Clara Callan""","""Richard Bruce Wright""","""2001""","""HarperFlamingo Canada""","""http://images.amazon.com/images/P/0002005018....","""http://images.amazon.com/images/P/0002005018....","""http://images.amazon.com/images/P/0002005018...."

In [80]:
users.head(2)

  "User-ID"                   "Location" "Age"
0       "1"         "nyc, new york, usa"   NaN
1       "2"  "stockton, california, usa"  "18"

In [81]:
ratings.head(2)

  "User-ID"        "ISBN" "Book-Rating"
0  "276725"  "034545104X"           "0"
1  "276726"  "0155061224"           "5"

In [82]:
books.columns

Index(['"ISBN"', '"Book-Title"', '"Book-Author"', '"Year-Of-Publication"',
       '"Publisher"', '"Image-URL-S"', '"Image-URL-M"', '"Image-URL-L"'],
      dtype='str')

In [83]:
books.shape

(250012, 8)

In [84]:
users.shape

(278700, 3)

In [85]:
ratings.shape

(1149780, 3)

In [86]:
books=books[['"ISBN"', '"Book-Title"', '"Book-Author"', '"Year-Of-Publication"',
       '"Publisher"','"Image-URL-L"']]

In [87]:
users.columns

Index(['"User-ID"', '"Location"', '"Age"'], dtype='str')

In [88]:
books.columns = books.columns.str.replace('"', '').str.strip()
users.columns = users.columns.str.replace('"', '').str.strip()
ratings.columns = ratings.columns.str.replace('"', '').str.strip()

In [89]:
books.rename(columns={
    'ISBN':'isbn',
    'Book-Title':'title',
    'Book-Author':'author',
    'Year_Of_Publication':'year',
    'publisher':'publisher',
    'Image-URL-L':'image_url',
},inplace=True)

In [90]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='str')

In [98]:
users.rename(columns={
    'User-ID':'user_id',
    'Location':'location',
    'Age':'age'
},inplace=True)

In [99]:
ratings.rename(columns={
    'User-ID':'user_id',
    'ISBN':'isbn',
    'Book-Rating':'book_rating'
},inplace=True)

In [100]:
ratings['user_id'].value_counts()

user_id
"11676"     13602
"198711"     7550
"153662"     6109
"98391"      5891
"35859"      5850
            ...
"276697"        1
"276706"        1
"276709"        1
"276721"        1
"276723"        1
Name: count, Length: 105283, dtype: int64

In [103]:
x=ratings['user_id'].value_counts()>200
x.value_counts()

count
False    104384
True        899
Name: count, dtype: int64

In [105]:
y=x[x].index
y

Index(['"11676"', '"198711"', '"153662"', '"98391"', '"35859"', '"212898"',
       '"278418"', '"76352"', '"110973"', '"235105"',
       ...
       '"260183"', '"9856"', '"28634"', '"44296"', '"59727"', '"73681"',
       '"155916"', '"188951"', '"268622"', '"274808"'],
      dtype='str', name='user_id', length=899)

In [109]:
rating=ratings[ratings['user_id'].isin(y)]
rating.head()

       user_id          isbn book_rating
1456  "277427"  "002542730X"        "10"
1457  "277427"  "0026217457"         "0"
1458  "277427"  "003008685X"         "8"
1459  "277427"  "0030615321"         "0"
1460  "277427"  "0060002050"         "0"

In [110]:
ratings_of_books=pd.merge(books,ratings,on='isbn')

In [111]:
ratings_of_books.head(2)

,isbn,title,author,Year-Of-Publication,Publisher,image_url,user_id,book_rating
0,"""0195153448""","""Classical Mythology""","""Mark P. O. Morford""","""2002""","""Oxford University Press""","""http://images.amazon.com/images/P/0195153448....","""2""","""0"""
1,"""0002005018""","""Clara Callan""","""Richard Bruce Wright""","""2001""","""HarperFlamingo Canada""","""http://images.amazon.com/images/P/0002005018....","""8""","""5"""

In [115]:
number_rating=ratings_of_books.groupby('title')['book_rating'].count().reset_index()

In [116]:
number_rating.head()

                                               title  book_rating
0  " A Light in the Storm: The Civil War Diary of...            4
1                           " Always Have Popsicles"            1
2            " Apple Magic (The Collector's series)"            1
3  " Ask Lily (Young Women of Faith: Lily Series,...            1
4  " Beyond IBM: Leadership Marketing and Finance...            1

In [123]:
number_rating.rename(columns={'book_rating':'num_of_ratings'},inplace=True)

In [124]:
final_rating=pd.merge(number_rating,ratings_of_books,on='title')

In [125]:
final_rating.head(2)

,title,num_of_ratings,isbn,author,Year-Of-Publication,Publisher,image_url,user_id,book_rating
0,""" A Light in the Storm: The Civil War Diary of...",4,"""0590567330""","""Karen Hesse""","""1999""","""Hyperion Books for Children""","""http://images.amazon.com/images/P/0590567330....","""18995""","""0"""
1,""" A Light in the Storm: The Civil War Diary of...",4,"""0590567330""","""Karen Hesse""","""1999""","""Hyperion Books for Children""","""http://images.amazon.com/images/P/0590567330....","""35859""","""0"""