In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
common_args = {
    "sep": ";",
    "encoding": "latin-1",
    "on_bad_lines": "skip"
}
books = pd.read_csv("books_data/books.csv", **common_args)
users = pd.read_csv("books_data/users.csv", **common_args)
ratings = pd.read_csv("books_data/ratings.csv", **common_args)

C:\Users\Shubham Joshi\AppData\Local\Temp\ipykernel_12008\1107790736.py:6: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("books_data/books.csv", **common_args)

In [3]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [4]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [5]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [6]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [7]:
books.shape

(271360, 8)

In [8]:
users.shape

(278858, 3)

In [9]:
ratings.shape

(1149780, 3)

In [10]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [11]:
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L']]

In [12]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='str')

In [13]:
books.columns = books.columns.str.replace('"', '').str.strip()
users.columns = users.columns.str.replace('"', '').str.strip()
ratings.columns = ratings.columns.str.replace('"', '').str.strip()

In [14]:
books.rename(columns={
    'ISBN':'isbn',
    'Book-Title':'title',
    'Book-Author':'author',
    'Year_Of_Publication':'year',
    'publisher':'publisher',
    'Image-URL-L':'image_url',
},inplace=True)

In [15]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='str')

In [16]:
users.rename(columns={
    'User-ID':'user_id',
    'Location':'location',
    'Age':'age'
},inplace=True)

In [17]:
ratings.rename(columns={
    'User-ID':'user_id',
    'ISBN':'isbn',
    'Book-Rating':'rating'
},inplace=True)

In [18]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [19]:
x=ratings['user_id'].value_counts()>200
x.value_counts()

count
False    104384
True        899
Name: count, dtype: int64

In [20]:
y=x[x].index
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,   9856,  28634,  44296,  59727,  73681, 155916, 188951, 268622,
       274808],
      dtype='int64', name='user_id', length=899)

In [21]:
rating=ratings[ratings['user_id'].isin(y)]
rating.head()

      user_id        isbn  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [22]:
ratings_of_books=pd.merge(books,ratings,on='isbn')

In [23]:
ratings_of_books.head(2)

,isbn,title,author,Year-Of-Publication,Publisher,image_url,user_id,rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,2,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,8,5

In [24]:
number_rating=ratings_of_books.groupby('title')['rating'].count().reset_index()

In [25]:
number_rating.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       4
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Ask Lily (Young Women of Faith: Lily Series, ...       1
4   Beyond IBM: Leadership Marketing and Finance ...       1

In [26]:
number_rating.rename(columns={'rating':'num_of_ratings'},inplace=True)

In [27]:
final_rating=pd.merge(number_rating,ratings_of_books,on='title')

In [28]:
final_rating.head(2)

,title,num_of_ratings,isbn,author,Year-Of-Publication,Publisher,image_url,user_id,rating
0,A Light in the Storm: The Civil War Diary of ...,4,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,18995,0
1,A Light in the Storm: The Civil War Diary of ...,4,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,35859,0

In [29]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [30]:
final_rating.columns

Index(['title', 'num_of_ratings', 'isbn', 'author', 'Year-Of-Publication',
       'Publisher', 'image_url', 'user_id', 'rating'],
      dtype='str')

In [31]:

final_rating.isna().sum()

title                  0
num_of_ratings         0
isbn                   0
author                 2
Year-Of-Publication    0
Publisher              2
image_url              4
user_id                0
rating                 0
dtype: int64

In [32]:
print(final_rating['rating'].dtype)
final_rating['rating'] = pd.to_numeric(final_rating['rating'], errors='coerce')
final_rating = final_rating[final_rating['num_of_ratings'] >= 50]

int64

In [33]:
print(final_rating.shape)
print(final_rating['rating'].isna().sum())
print(final_rating.head())

(285518, 9)
0
              title  num_of_ratings        isbn        author  \
561  10 Lb. Penalty              61  0399143025  Dick Francis
562  10 Lb. Penalty              61  0399143025  Dick Francis
563  10 Lb. Penalty              61  0399143025  Dick Francis
564  10 Lb. Penalty              61  0399143025  Dick Francis
565  10 Lb. Penalty              61  0399143025  Dick Francis

    Year-Of-Publication         Publisher  \
561                1997  Putnam Pub Group
562                1997  Putnam Pub Group
563                1997  Putnam Pub Group
564                1997  Putnam Pub Group
565                1997  Putnam Pub Group

                                             image_url  user_id  rating
561  http://images.amazon.com/images/P/0399143025.0...    27740       0
562  http://images.amazon.com/images/P/0399143025.0...    55548       0
563  http://images.amazon.com/images/P/0399143025.0...    94923       0
564  http://images.amazon.com/images/P/0399143025.0...   108700       0
565  http://images.amazon.com/images/P/0399143025.0...   111747       8

In [34]:
book_pivot=final_rating.pivot_table(columns='user_id',index='title',values='rating')

In [35]:
book_pivot

user_id,8,9,14,16,17,19,23,26,32,39,...,278820,278824,278828,278832,278836,278843,278844,278846,278851,278854
title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stardust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
book_pivot.fillna(0, inplace=True)

user_id,8,9,14,16,17,19,23,26,32,39,...,278820,278824,278828,278832,278836,278843,278844,278846,278851,278854
title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
from scipy.sparse import csr_matrix

In [38]:
book_sparse=csr_matrix(book_pivot)

In [39]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 113442 stored elements and shape (2444, 47994)>

In [40]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [41]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [42]:
book_pivot.iloc[237,:]

user_id
8         0.0
9         6.0
14        0.0
16        0.0
17        0.0
         ...
278843    0.0
278844    0.0
278846    0.0
278851    0.0
278854    0.0
Name: Beloved (Plume Contemporary Fiction), Length: 47994, dtype: float64

In [43]:
distance, suggestion=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=10)

In [45]:
distance

array([[ 0.        , 73.70888685, 74.13501197, 74.14849965, 74.25631286,
        74.42445835, 74.43789358, 74.4848978 , 74.76630257, 74.8465096 ]])

In [46]:
suggestion

array([[ 237, 1391, 1713,  770,   65,  284, 2423,  679,   99, 1956]])

In [47]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Beloved (Plume Contemporary Fiction)', 'Reasonable Doubt',
       'The Blooding', 'Ground Zero and Beyond', 'A Secret Affair',
       'Blood and Gold (Rice, Anne, Vampire Chronicles.)', 'Women in His Life',
       'Flight of the Old Dog', 'About Face', 'The Juror'],
      dtype='str', name='title')

In [48]:
book_names=book_pivot.index

In [49]:
book_names

Index(['10 Lb. Penalty', '16 Lighthouse Road', '1984', '1st to Die: A Novel',
       '2010: Odyssey Two', '204 Rosewood Lane', '2061: Odyssey Three',
       '24 Hours', '2nd Chance', '3rd Degree',
       ...
       'YOU BELONG TO ME', 'Year of Wonders', 'You Belong To Me',
       'You Shall Know Our Velocity', 'Young Wives',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"',
       '\Surely You're Joking, Mr. Feynman!\": Adventures of a Curious Character"',
       'stardust'],
      dtype='str', name='title', length=2444)

In [50]:
book_names[4]

'2010: Odyssey Two'

In [51]:
final_rating.iloc[4]

title                                                     10 Lb. Penalty
num_of_ratings                                                        61
isbn                                                          0399143025
author                                                      Dick Francis
Year-Of-Publication                                                 1997
Publisher                                               Putnam Pub Group
image_url              http://images.amazon.com/images/P/0399143025.0...
user_id                                                           111747
rating                                                                 8
Name: 565, dtype: object

In [52]:
book_name=[]
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [53]:
book_name

[Index(['Beloved (Plume Contemporary Fiction)', 'Reasonable Doubt',
        'The Blooding', 'Ground Zero and Beyond', 'A Secret Affair',
        'Blood and Gold (Rice, Anne, Vampire Chronicles.)', 'Women in His Life',
        'Flight of the Old Dog', 'About Face', 'The Juror'],
       dtype='str', name='title')]

In [55]:
ids_index=[]
for name in book_name[0]:
    ids=np.where(final_rating['title']==name)[0][0]
    ids_index.append(ids)

In [56]:
ids_index

[np.int64(28639),
 np.int64(152706),
 np.int64(188652),
 np.int64(85418),
 np.int64(8882),
 np.int64(33301),
 np.int64(283502),
 np.int64(75706),
 np.int64(13240),
 np.int64(220279)]

In [58]:
for idx in ids_index:
    url=final_rating.iloc[idx]['image_url']
    print(url)

http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0804107491.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0553282816.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/1401088945.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0061012289.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0345409329.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0345345738.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0425108937.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0821770209.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446518859.01.LZZZZZZZ.jpg

In [61]:

import pickle
pickle.dump(model,open('artifacts/model.pkl','wb'))
pickle.dump(book_names,open('artifacts/book_names.pkl','wb'))
pickle.dump(final_rating,open('artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot,open('artifacts/book_pivot.pkl','wb'))

In [71]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            books = book_pivot.index[suggestion[i]]
            for j in books:
                if j == book_name:
                    print(f"You searched '{book_name}'\n")
                    print("The suggestion books are: \n")
                else:
                    print(j)

In [73]:
book_name='A Case of Need'
recommend_book(book_name)

You searched 'A Case of Need'

The suggestion books are:

Man From St Petersburg
Women in His Life
Breaking Point (Tom Clancy's Net Force, No. 4)
The Blooding
Reasonable Doubt